# Generated by Django 4.1.3 on 2022-11-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_teg'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tegs',
            field=models.ManyToManyField(to='blog.teg'),
        ),
    ]
