# Generated by Django 4.1.3 on 2022-11-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_tegs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tegs',
            field=models.ManyToManyField(blank=True, to='blog.teg', verbose_name='Теги'),
        ),
    ]
