# Generated by Django 4.1.3 on 2023-01-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcategory_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='meta_title',
        ),
    ]
