# Generated by Django 4.1.3 on 2023-01-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tag_meta_description_tag_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='name',
        ),
    ]
