# Generated by Django 4.1.3 on 2023-02-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_title_article_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('e_mail', models.CharField(max_length=255, verbose_name='e_mail')),
                ('text', models.TextField(verbose_name='Комент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комен',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
