# Generated by Django 4.1.3 on 2023-02-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcomets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomets',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Статья'),
        ),
    ]
