# Generated by Django 4.1.3 on 2022-12-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_parser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parser',
            new_name='parent',
        ),
    ]
