# Generated by Django 4.1.3 on 2023-02-21 16:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Содержания'),
        ),
    ]
