# Generated by Django 4.1.3 on 2023-02-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_user'),
        ('main', '0003_productpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPage',
            new_name='ProductSet',
        ),
    ]
